# Generated by Django 5.1.3 on 2024-11-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ideal_temperature_min", models.FloatField()),
                ("ideal_temperature_max", models.FloatField()),
                ("ideal_rainfall_min", models.FloatField()),
                ("ideal_rainfall_max", models.FloatField()),
            ],
        ),
    ]
