# Generated by Django 5.1.3 on 2024-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="crop",
            name="government_policies",
            field=models.TextField(default="No policies available"),
        ),
        migrations.AddField(
            model_name="crop",
            name="humidity_level",
            field=models.CharField(default="50", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="ideal_soil_type",
            field=models.CharField(default="Loamy", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="ideal_sunlight",
            field=models.CharField(default="Full Sun", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="pesticides_required",
            field=models.TextField(default="None"),
        ),
        migrations.AddField(
            model_name="crop",
            name="recommended_pesticides",
            field=models.TextField(default="None"),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_moisture_level",
            field=models.CharField(default="Moderate", max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="special_care",
            field=models.TextField(default="None"),
        ),
    ]
